<div class="container my-3">
		<div class="card">
			<div class="card-body">
				<h4>Login</h4>
				<hr>
				<form action="/autenticar" method="post">
					<div class="form-group">
						<label class="form-label">E-mail</label>
						<input class="form-control" type="text" name="email">
					</div>
					<div class="form-group">
						<label class="form-label">Senha</label>
						<input class="form-control" type="password" name="senha">
					</div>
					<button type="submit" class="btn btn-success">Acessar</button>
					<? if($this->view->login == 'erro'){ ?>
						<div class="form-text text-danger">E-mail e/ou senha invalidos. Verifique e tente novamente!</div>
					<? } ?>
				</form>
				<div>Não é cadastrado ainda? <a href="/inscreverse">Clique aqui para cadastrar!</a></div>
			</div>
		</div>
</div>