<div class="container my-3">
	<div class="card">
		<div class="card-body">
			<h4>Cadastrar</h4>
			<hr>
			<form action="/registrar" method="post">
				<div class="form-group">
					<label class="form-label">Nome</label>
					<input class="form-control" type="text" name="nome" value="<?=$this->view->usuario['nome']?>">
				</div>
				<div class="form-group">
					<label class="form-label">E-mail</label>
					<input class="form-control" type="text" name="email" value="<?=$this->view->usuario['email']?>">
				</div>
				<div class="form-group">
					<label class="form-label">Senha</label>
					<input class="form-control" type="password" name="senha">
				</div>
				<button type="submit" class="btn btn-success">Acessar</button>
				<?php if($this->view->erroCadastro) {?>
					<div class="form-text text-danger">Verifique os dados e tente novamente!</div>
				<?php } ?>
			</form>

		</div>
	</div>
</div>