<div class="container app">
	<div class="row">
		<div class="col-md-3 menu">
			<ul class="list-group">
				<li class="list-group-item"><a href="/tarefas_pendentes">Tarefas pendentes</a></li>
				<li class="list-group-item"><a href="/nova_tarefa">Nova tarefa</a></li>
				<li class="list-group-item active"><a href="/todas_tarefas">Todas tarefas</a></li>
			</ul>
		</div>

		<div class="col-md-9">
			<div class="container pagina">
				<div class="row">
					<div class="col">
						<h4>Todas tarefas</h4>
						<hr />
						<? foreach($this->view->tarefas as $indice => $tarefa){ ?>
							<div class="row mb-3 d-flex align-items-center tarefa">
								<div class="col-sm-9" id="tarefa_<?=$tarefa['id']?>">
									<?=$tarefa['tarefa']?> (<?=$tarefa['status']?>) <?=$tarefa['id']?>
								</div>
								<div class="col-sm-3 mt-2 d-flex justify-content-between">
									<i class="fas fa-trash-alt fa-lg text-danger" onclick="removerTarefaTodas(<?=$tarefa['id']?>)"></i>
									<? if($tarefa['status'] == 'pendente'){?>
										<i class="fas fa-edit fa-lg text-info" onclick="editarTaefaTodas(<?=$tarefa['id']?>,'<?=$tarefa['tarefa']?>')"></i>
										<i class="fas fa-check-square fa-lg text-success" onclick="marcarRealizadoTarefaTodas(<?=$tarefa['id']?>)"></i>
									<?}?>
								</div>
							</div>
						<? } ?>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
		